# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Player.create(name: 'Ryan Kelly', position: 'C', number: 78)
Player.create(name: 'Quenton Nelson', position: 'C/G', number: 56)
Player.create(name: 'T.J. Carrie', position: 'CB', number: 38)
Player.create(name: 'Anthony Chesley', position: 'CB', number: 47)
Player.create(name: 'Kenny Moore II', position: 'CB', number: 23)
Player.create(name: 'Xavier Rhodes', position: 'CB', number: 27)
Player.create(name: 'Isaiah Rodgers', position: 'CB', number: 34)
Player.create(name: 'Rock Ya-Sin', position: 'CB', number: 26)
Player.create(name: 'Ben Banogu', position: 'DE', number: 52)
Player.create(name: 'Al-Quadin Muhammad', position: 'DE', number: 97)
Player.create(name: 'Dayo Odeyingbo', position: 'DE', number: 54)
Player.create(name: 'Kwity Paye', position: 'DE', number: 51)
Player.create(name: 'Isaac Rochell', position: 'DE', number: 91)
Player.create(name: 'Kemoko Turay', position: 'DE', number: 57)
Player.create(name: 'DeForest BUckner', position: 'DT', number: 99)
Player.create(name: 'Taylor Stallworth', position: 'DT', number: 95)
Player.create(name: 'Grover Stewart', position: 'DT', number: 96)
Player.create(name: 'Antwaun Woods', position: 'DT', number: 96)
Player.create(name: 'Mark Glowinski', position: 'G', number: 64)
Player.create(name: 'Danny Pinter', position: 'G', number: 63)
Player.create(name: 'Chris Reed', position: 'G', number: 62)
Player.create(name: 'Will Fries', position: 'G/T', number: 75)
Player.create(name: 'Michael Badgley', position: 'K', number: 6)
Player.create(name: 'Matthew Adams', position: 'LB', number: 49)
Player.create(name: 'Zaire Franklin', position: 'LB', number: 44)
Player.create(name: 'Jordan Glasgow', position: 'LB', number: 59)
Player.create(name: 'Darius Leonard', position: 'LB', number: 53)
Player.create(name: 'Bobby Okereke', position: 'LB', number: 58)
Player.create(name: 'E.J. Speed', position: 'LB', number: 45)
Player.create(name: 'Luke Rhodes', position: 'LS', number: 46)
Player.create(name: 'Eric Fisher', position: 'OT', number: 79)
Player.create(name: 'Rigoberto Sanchez', position: 'P', number: 8)
Player.create(name: 'Sam Ehlinger', position: 'QB', number: 4)
Player.create(name: 'Carson Wentz', position: 'QB', number: 2)
Player.create(name: 'Nyheim Hines', position: 'RB', number: 21)
Player.create(name: 'Deon Jackson', position: 'RB', number: 35)
Player.create(name: 'Marlon Mack', position: 'RB', number: 25)
Player.create(name: 'Jonathan Taylor', position: 'RB', number: 28)
Player.create(name: 'Josh Jones', position: 'S', number: 36)
Player.create(name: 'George Odum', position: 'S', number: 30)
Player.create(name: 'Andrew Sendejo', position: 'S', number: 42)
Player.create(name: 'Julien Davenport', position: 'T', number: 73)
Player.create(name: 'Matt Pryor', position: 'T', number: 69)
Player.create(name: 'Braden Smith', position: 'T/G', number: 72)
Player.create(name: 'Mo Alie-Cox', position: 'TE', number: 81)
Player.create(name: 'Jack Doyle', position: 'TE', number: 84)
Player.create(name: 'Kylen Granson', position: 'TE', number: 83)
Player.create(name: 'Ashton Dulin', position: 'WR', number: 16)
Player.create(name: 'T.Y. Hilton', position: 'WR', number: 13)
Player.create(name: 'Zach Pascal', position: 'WR', number: 14)
Player.create(name: 'Dezmon Patmon', position: 'WR', number: 10)
Player.create(name: 'Michael Pittman Jr.', position: 'WR', number: 11)
Player.create(name: 'Mike Strachan', position: 'WR', number: 17)